sudo: required
language: nix
cache:
  timeout: 1000
  directories:
  - /nix/store
branches:
  only:
  - master
  - vector
notifications:
  email:
  - false
script:
- nix-shell --pure --run 'make -j $NIX_BUILD_CORES -C proofs'
- nix-shell --pure --run 'make -C compiler CIL build tests-ci'
